<a href="https://colab.research.google.com/github/omvaidya1/specialtask_omvaidya1/blob/main/specialtask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [6]:

from google.colab import files
upload=files.upload()

Saving pokemon1.csv to pokemon1 (1).csv

In [7]:
filepath='/content/pokemon1.csv'
df=pd.read_csv(filepath)
df

,id,name,base_experience,height,weight,types,abilities,moves,stats
0,1,bulbasaur,64,7,69,"grass, poison","overgrow, chlorophyll","razor-wind, swords-dance, cut, bind, vine-whip","hp=45, attack=49, defense=49, special-attack=6..."
1,2,ivysaur,142,10,130,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=60, attack=62, defense=63, special-attack=8..."
2,3,venusaur,236,20,1000,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=80, attack=82, defense=83, special-attack=1..."
3,4,charmander,62,6,85,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=39, attack=52, defense=43, special-attack=6..."
4,5,charmeleon,142,11,190,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=58, attack=64, defense=58, special-attack=8..."
...,...,...,...,...,...,...,...,...,...
1297,10273,ogerpon-wellspring-mask,275,12,398,"grass, water",water-absorb,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1298,10274,ogerpon-hearthflame-mask,275,12,398,"grass, fire",mold-breaker,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1299,10275,ogerpon-cornerstone-mask,275,12,398,"grass, rock",sturdy,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1300,10276,terapagos-terastal,90,3,160,normal,tera-shell,"headbutt, body-slam, take-down, double-edge, roar","hp=95, attack=95, defense=110, special-attack=..."
1301,10277,terapagos-stellar,90,17,770,normal,teraform-zero,"headbutt, body-slam, take-down, double-edge, roar","hp=160, attack=105, defense=110, special-attac..."

In [8]:
df.head()

,id,name,base_experience,height,weight,types,abilities,moves,stats
0,1,bulbasaur,64,7,69,"grass, poison","overgrow, chlorophyll","razor-wind, swords-dance, cut, bind, vine-whip","hp=45, attack=49, defense=49, special-attack=6..."
1,2,ivysaur,142,10,130,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=60, attack=62, defense=63, special-attack=8..."
2,3,venusaur,236,20,1000,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=80, attack=82, defense=83, special-attack=1..."
3,4,charmander,62,6,85,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=39, attack=52, defense=43, special-attack=6..."
4,5,charmeleon,142,11,190,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=58, attack=64, defense=58, special-attack=8..."

In [9]:
df.tail()

,id,name,base_experience,height,weight,types,abilities,moves,stats
1297,10273,ogerpon-wellspring-mask,275,12,398,"grass, water",water-absorb,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1298,10274,ogerpon-hearthflame-mask,275,12,398,"grass, fire",mold-breaker,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1299,10275,ogerpon-cornerstone-mask,275,12,398,"grass, rock",sturdy,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1300,10276,terapagos-terastal,90,3,160,normal,tera-shell,"headbutt, body-slam, take-down, double-edge, roar","hp=95, attack=95, defense=110, special-attack=..."
1301,10277,terapagos-stellar,90,17,770,normal,teraform-zero,"headbutt, body-slam, take-down, double-edge, roar","hp=160, attack=105, defense=110, special-attac..."

In [10]:
df.shape

(1302, 9)

In [11]:
df.columns

Index(['id', 'name', 'base_experience', 'height', 'weight', 'types',
       'abilities', 'moves', 'stats'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1302 entries, 0 to 1301
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1302 non-null   int64
 1   name             1302 non-null   object
 2   base_experience  1302 non-null   int64
 3   height           1302 non-null   int64
 4   weight           1302 non-null   int64
 5   types            1302 non-null   object
 6   abilities        1302 non-null   object
 7   moves            1268 non-null   object
 8   stats            1302 non-null   object
dtypes: int64(4), object(5)
memory usage: 91.7+ KB

In [13]:
df.describe()

                 id  base_experience       height        weight
count   1302.000000      1302.000000  1302.000000   1302.000000
mean    2560.927803       161.943932    20.467742    980.863287
std     3949.887748        82.532554    54.180316   1972.645170
min        1.000000        36.000000     1.000000      0.000000
25%      326.250000        71.000000     5.000000     89.250000
50%      651.500000       165.000000    10.000000    315.500000
75%      976.750000       222.500000    16.000000    818.000000
max    10277.000000       608.000000  1000.000000  10000.000000

In [14]:
df.dtypes

id                  int64
name               object
base_experience     int64
height              int64
weight              int64
types              object
abilities          object
moves              object
stats              object
dtype: object

In [15]:
df.isnull().sum()

id                  0
name                0
base_experience     0
height              0
weight              0
types               0
abilities           0
moves              34
stats               0
dtype: int64

In [16]:
df.nunique()

id                 1302
name               1302
base_experience     201
height               85
weight              533
types               221
abilities           707
moves               812
stats              1142
dtype: int64

In [17]:
df.sample(5)

,id,name,base_experience,height,weight,types,abilities,moves,stats
731,732,trumbeak,124,6,148,"normal, flying","keen-eye, skill-link, pickup","swords-dance, fly, fury-attack, take-down, growl","hp=55, attack=85, defense=50, special-attack=4..."
252,253,grovyle,142,9,216,grass,"overgrow, unburden","pound, mega-punch, thunder-punch, swords-dance...","hp=50, attack=65, defense=45, special-attack=8..."
273,274,nuzleaf,119,10,280,"grass, dark","chlorophyll, early-bird, pickpocket","pound, razor-wind, swords-dance, cut, mega-kick","hp=70, attack=70, defense=40, special-attack=6..."
182,183,marill,88,4,85,"water, fairy","thick-fat, huge-power, sap-sipper","mega-punch, ice-punch, slam, mega-kick, headbutt","hp=70, attack=20, defense=50, special-attack=2..."
449,450,hippowdon,184,20,3000,ground,"sand-stream, sand-force","sand-attack, headbutt, tackle, body-slam, take...","hp=108, attack=112, defense=118, special-attac..."

In [18]:
df.value_counts()

id     name                         base_experience  height  weight  types           abilities                        moves                                                         stats
10277  terapagos-stellar            90               17      770     normal          teraform-zero                    headbutt, body-slam, take-down, double-edge, roar             hp=160, attack=105, defense=110, special-attack=130, special-defense=110, speed=85    1
1      bulbasaur                    64               7       69      grass, poison   overgrow, chlorophyll            razor-wind, swords-dance, cut, bind, vine-whip                hp=45, attack=49, defense=49, special-attack=65, special-defense=65, speed=45         1
2      ivysaur                      142              10      130     grass, poison   overgrow, chlorophyll            swords-dance, cut, bind, vine-whip, headbutt                  hp=60, attack=62, defense=63, special-attack=80, special-defense=80, speed=60         1
3      venusaur                     236              20      1000    grass, poison   overgrow, chlorophyll            swords-dance, cut, bind, vine-whip, headbutt                  hp=80, attack=82, defense=83, special-attack=100, special-defense=100, speed=80       1
10261  squawkabilly-yellow-plumage  146              6       24      normal, flying  intimidate, hustle, sheer-force  fly, fury-attack, take-down, double-edge, growl               hp=82, attack=96, defense=51, special-attack=45, special-defense=51, speed=92         1
                                                                                                                                                                                                                                                                         ..
9      blastoise                    239              16      855     water           torrent, rain-dish               mega-punch, ice-punch, mega-kick, headbutt, tackle            hp=79, attack=83, defense=100, special-attack=85, special-defense=105, speed=78       1
8      wartortle                    142              10      225     water           torrent, rain-dish               mega-punch, ice-punch, mega-kick, headbutt, tackle            hp=59, attack=63, defense=80, special-attack=65, special-defense=80, speed=58         1
7      squirtle                     63               5       90      water           torrent, rain-dish               mega-punch, ice-punch, mega-kick, headbutt, tackle            hp=44, attack=48, defense=65, special-attack=50, special-defense=64, speed=43         1
6      charizard                    240              17      905     fire, flying    blaze, solar-power               mega-punch, fire-punch, thunder-punch, scratch, swords-dance  hp=78, attack=84, defense=78, special-attack=109, special-defense=85, speed=100       1
5      charmeleon                   142              11      190     fire            blaze, solar-power               mega-punch, fire-punch, thunder-punch, scratch, swords-dance  hp=58, attack=64, defense=58, special-attack=80, special-defense=65, speed=80         1
Name: count, Length: 1268, dtype: int64